name: "MLSpec Sample Action - Train"
description: "Sample Action Example: Training"
author: "aronchick"
inputs:
  METASTORE_CREDENTIALS:
    description: "Some text"
    required: true
branding:
  icon: "chevron-up"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
