# Integration test variables
INPUT_integration_tests_schemas_dir_name: 'integration/.parameters/schemas'

# Variables to hand to the docker container to mock up a real run
INPUT_container_repo_name: mlspec
INPUT_container_name: mlspeclib-action-samples-train:latest
INPUT_parameters_directory: '/src/parameters'
INPUT_schemas_directory: '/src/parameters/test_schemas'
INPUT_execution_parameters_raw:
  schema_version: 999.0.1
  nodes: 8
  cpu_per_node: 8
  ram_per_node: 64Gi
  gpu_required: true
  output_path: test/models/output
  training_params:
    learning_rate: 0.1
    loss: 0.3
    batch_size: 1000
    epoch: 50
    optimizer: ['SGD']
    other_tags:
      pii: false
      data_sha: 8b03f70
  schema_type: training_run
  base_image: ubuntu1804
  machine_type: NDv2
INPUT_step_name: 'train'
INPUT_workflow:
  schema_type: workflow
  schema_version: 999.0.1
  steps:
    process_data:
      input:
        schema_type: data_source
        schema_version: 999.0.1
      execution:
        schema_type: data_process_run
        schema_version: 999.0.1
      output:
        schema_type: data_result
        schema_version: 999.0.1
      next: train
    train:
      previous: process_data
      input:
        schema_type: data_result
        schema_version: 999.0.1
      execution:
        schema_type: training_run
        schema_version: 999.0.1
      output:
        schema_type: training_result
        schema_version: 999.0.1
      next: package
    package:
      previous: train
      input:
        schema_type: training_result
        schema_version: 999.0.1
      execution:
        schema_type: package_run
        schema_version: 999.0.1
      output:
        schema_type: package_result
        schema_version: 999.0.1
INPUT_input_parameters_raw:
  schema_version: 999.0.1
  schema_type: data_result
  run_id: 6a9a5931-1c1d-47cc-aaf3-ad8b03f70575
  step_id: 433b4d99-042d-47c5-8c2f-6a4f5094510e
  run_date: 1970-01-08 00:00:00.00000
  data_output_path: tests/data/data_output.csv
  data_statistics_path: tests/data/data_stats.csv
  data_schemas_path: tests/data/data_schemas.yaml
  feature_file_path: tests/data/feature_file.yaml